abstract class SochialState{}
class SochialIntialState extends SochialState{}
class SochialLoadingState extends SochialState{}
class SochialSucssesState extends SochialState{}
class SochialErorrState extends SochialState{}
class SochialChangeState extends SochialState{}
class SochialChangePostState extends SochialState{}
class SochialImageSucssesState extends SochialState{}
class SochialCoverSucssesState extends SochialState{}
class SochialUpDateimageSucssesState extends SochialState{}
class SochialUpDateimageErorrState extends SochialState{}
class SochialUpDateCoverSucssesState extends SochialState{}
class SochialUpDateCoverErorrState extends SochialState{}
class SochialUpDateAllSucssesState extends SochialState{}
class SochialUpDateAllErorrState extends SochialState{}
class SochialUpDateAllLoadingState extends SochialState{}
class SochialLoading1State extends SochialState{}
class SochialSucssesS1tate extends SochialState{}
class SochialErorr1State extends SochialState{}
class SochialLoadingImageState extends SochialState{}
class SochialLoadingCoverState extends SochialState{}
class SochialPostSucssesState extends SochialState{}
class SochialPostSucssesState1 extends SochialState{}
class SochialPostErorrState extends SochialState{}
class SochialPostLoadingImageState extends SochialState{}
class SochialRemovePostImageState extends SochialState{}
class SochialGetPostLoadingState extends SochialState{}
class SochialGetPostSucssesState extends SochialState{}
class SochialGetPostErorr1State extends SochialState{}
class SochialLikePostSucssesState extends SochialState{}
class SochialLikePostErorr1State extends SochialState{}
class SochialintLikePostSucssesState extends SochialState{}
class SochialintLikePostErorr1State extends SochialState{}
class SochiaChatSucssesState extends SochialState{}
class SochialChatErorr1State extends SochialState{}
class SochialGetMassageSucssesState extends SochialState{}
class SochialGetMassageErorr1State extends SochialState{}

